//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinFS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JoinFS.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to acquire access to the X-Plane aircraft. This is usually because another plugin has already been granted access. Try disabling the other plugin to give JoinFS access..
        /// </summary>
        internal static string AcquiredWarning {
            get {
                return ResourceManager.GetString("AcquiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to inject all aircraft. You should add more AI Aircraft to the Flight Configuration menu in X-Plane..
        /// </summary>
        internal static string AircraftWarning {
            get {
                return ResourceManager.GetString("AircraftWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airliner.
        /// </summary>
        internal static string Airliner {
            get {
                return ResourceManager.GetString("Airliner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import your JoinFS settings from v3.1.6?.
        /// </summary>
        internal static string AskImport {
            get {
                return ResourceManager.GetString("AskImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimConnect is required for Microsoft Flight Simulator, Prepar3D and FSX. Do you wish to download it?.
        /// </summary>
        internal static string AskSimConnect {
            get {
                return ResourceManager.GetString("AskSimConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first start a simulator before assigning variables..
        /// </summary>
        internal static string AssignVariablesWarning {
            get {
                return ResourceManager.GetString("AssignVariablesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATC Mode is enabled. This allows aircraft to be visible on radar, but has an adverse effect on the smooth movement of aircraft..
        /// </summary>
        internal static string AtcModeEnabled {
            get {
                return ResourceManager.GetString("AtcModeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With ATC mode enabled, network aircraft will be visible on the default radar. However, some aircraft may act in a strange manner while ATC mode is enabled..
        /// </summary>
        internal static string AtcWarning {
            get {
                return ResourceManager.GetString("AtcWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patreon.
        /// </summary>
        internal static string BecomeAPatron {
            get {
                return ResourceManager.GetString("BecomeAPatron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomber.
        /// </summary>
        internal static string Bomber {
            get {
                return ResourceManager.GetString("Bomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Me A Coffee.
        /// </summary>
        internal static string Coffee {
            get {
                return ResourceManager.GetString("Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the JoinFS communications system. This area shows incoming messages, hub information and event notifications. On the left, select the channels to receive and transmit. Right-click to change colours. Type a message in the box below then click &apos;Send&apos; or press the enter key. Type &apos;.help&apos; for commands..
        /// </summary>
        internal static string CommsWelcome {
            get {
                return ResourceManager.GetString("CommsWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Flight Plan....
        /// </summary>
        internal static string CopyFlightPlan {
            get {
                return ResourceManager.GetString("CopyFlightPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close JoinFS and download the new version?.
        /// </summary>
        internal static string DownloadNew {
            get {
                return ResourceManager.GetString("DownloadNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first start a simulator before editing substitutions..
        /// </summary>
        internal static string EditMatchingWarning {
            get {
                return ResourceManager.GetString("EditMatchingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Model Masquerading.
        /// </summary>
        internal static string EditModelMasquerading {
            get {
                return ResourceManager.GetString("EditModelMasquerading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Model Matching.
        /// </summary>
        internal static string EditModelMatching {
            get {
                return ResourceManager.GetString("EditModelMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Cockpit.
        /// </summary>
        internal static string EnterCockpit {
            get {
                return ResourceManager.GetString("EnterCockpit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter.
        /// </summary>
        internal static string Fighter {
            get {
                return ResourceManager.GetString("Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string FoundPrefix {
            get {
                return ResourceManager.GetString("FoundPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model(s).
        /// </summary>
        internal static string FoundSuffix {
            get {
                return ResourceManager.GetString("FoundSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FourProp.
        /// </summary>
        internal static string FourProp {
            get {
                return ResourceManager.GetString("FourProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating CSL objects may take several minutes. You may need to restart X-Plane when complete..
        /// </summary>
        internal static string GenerateCslWarning {
            get {
                return ResourceManager.GetString("GenerateCslWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glider.
        /// </summary>
        internal static string Glider {
            get {
                return ResourceManager.GetString("Glider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to install the plugin for X-Plane?.
        /// </summary>
        internal static string InstallPlugin {
            get {
                return ResourceManager.GetString("InstallPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid height adjustment.
        /// </summary>
        internal static string InvalidHeight {
            get {
                return ResourceManager.GetString("InvalidHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid join address. Either select from the address book or use an address in a format described in the manual..
        /// </summary>
        internal static string InvalidJoinAddress {
            get {
                return ResourceManager.GetString("InvalidJoinAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port number.
        /// </summary>
        internal static string InvalidPortPrefix {
            get {
                return ResourceManager.GetString("InvalidPortPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs to be in the range 1-65535.
        /// </summary>
        internal static string InvalidPortSuffix {
            get {
                return ResourceManager.GetString("InvalidPortSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid substitution.
        /// </summary>
        internal static string InvalidSubstitution {
            get {
                return ResourceManager.GetString("InvalidSubstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the X-Plane plugins folder.
        /// </summary>
        internal static string LocatePluginFolder {
            get {
                return ResourceManager.GetString("LocatePluginFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JoinFS is already running on this system.
        /// </summary>
        internal static string MaxInstances {
            get {
                return ResourceManager.GetString("MaxInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model list is empty for this simulator. Would you like to scan for models now?.
        /// </summary>
        internal static string ModelListEmpty {
            get {
                return ResourceManager.GetString("ModelListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version available. Would you like to install it?.
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        internal static string NewVersionStatus {
            get {
                return ResourceManager.GetString("NewVersionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner of the aircraft has not given permission for you to enter..
        /// </summary>
        internal static string NoPermissionCockpit {
            get {
                return ResourceManager.GetString("NoPermissionCockpit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find substitute model.
        /// </summary>
        internal static string NoSubstituteModel {
            get {
                return ResourceManager.GetString("NoSubstituteModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This recording is an old version and no longer supported with this version of JoinFS.
        /// </summary>
        internal static string OldRecording {
            get {
                return ResourceManager.GetString("OldRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate CSL objects for installed X-Plane aircraft during a scan..
        /// </summary>
        internal static string Option_GenerateCsl {
            get {
                return ResourceManager.GetString("Option_GenerateCsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip CSL objects already done during a scan..
        /// </summary>
        internal static string Option_SkipCsl {
            get {
                return ResourceManager.GetString("Option_SkipCsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the maximum distance in nautical miles that aircraft will be injected into the simulator..
        /// </summary>
        internal static string Options_ActivityCircle {
            get {
                return ResourceManager.GetString("Options_ActivityCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the airport this ATC is controlling from. For example, &apos;EGLL&apos;..
        /// </summary>
        internal static string Options_Airport {
            get {
                return ResourceManager.GetString("Options_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ATC mode. Other users will see you marked as ATC..
        /// </summary>
        internal static string Options_Atc {
            get {
                return ResourceManager.GetString("Options_Atc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For JoinFS-CONSOLE, run as a background task with no keyboard input..
        /// </summary>
        internal static string Options_Background {
            get {
                return ResourceManager.GetString("Options_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new session if hub mode is not enabled.
        /// </summary>
        internal static string Options_Create {
            get {
                return ResourceManager.GetString("Options_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the distance in meters at which your aircraft will be positioned behind another object. Applies to follow option in the aircraft list..
        /// </summary>
        internal static string Options_Follow {
            get {
                return ResourceManager.GetString("Options_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the global session immediately..
        /// </summary>
        internal static string Options_Global {
            get {
                return ResourceManager.GetString("Options_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show usage details..
        /// </summary>
        internal static string Options_Help {
            get {
                return ResourceManager.GetString("Options_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the X-Plane plugin for JoinFS.
        /// </summary>
        internal static string Options_InstallPlugin {
            get {
                return ResourceManager.GetString("Options_InstallPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join a session at the specified address.
        /// </summary>
        internal static string Options_Join {
            get {
                return ResourceManager.GetString("Options_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch JoinFS minimized on the Windows task bar. Quiet mode..
        /// </summary>
        internal static string Options_Minimize {
            get {
                return ResourceManager.GetString("Options_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a nickname. Others will be able to see this in the aircraft and user lists..
        /// </summary>
        internal static string Options_Nickname {
            get {
                return ResourceManager.GetString("Options_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run JoinFS as a background process without any windows or UI..
        /// </summary>
        internal static string Options_NoGui {
            get {
                return ResourceManager.GetString("Options_NoGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not connect to the simulator at launch..
        /// </summary>
        internal static string Options_NoSim {
            get {
                return ResourceManager.GetString("Options_NoSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a JoinFS recorder file and play back the recording in the current session. Other users will need to enable &apos;Allow Multiple Objects&apos;. See Manual..
        /// </summary>
        internal static string Options_Play {
            get {
                return ResourceManager.GetString("Options_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the specified IP port for connections to other sessions. The default port is 6112..
        /// </summary>
        internal static string Options_Port {
            get {
                return ResourceManager.GetString("Options_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate all instances of JoinFS currently running on this machine..
        /// </summary>
        internal static string Options_Quit {
            get {
                return ResourceManager.GetString("Options_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately start recording..
        /// </summary>
        internal static string Options_Record {
            get {
                return ResourceManager.GetString("Options_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the previous session..
        /// </summary>
        internal static string Options_Rejoin {
            get {
                return ResourceManager.GetString("Options_Rejoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the simulator root folder..
        /// </summary>
        internal static string Options_SimFolder {
            get {
                return ResourceManager.GetString("Options_SimFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Plane plugin successfully installed.
        /// </summary>
        internal static string PluginInstalled {
            get {
                return ResourceManager.GetString("PluginInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recorder is empty. Choose &apos;Recorder|Record&apos; from the menu to make a recording..
        /// </summary>
        internal static string RecorderEmpty {
            get {
                return ResourceManager.GetString("RecorderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder.
        /// </summary>
        internal static string RecorderStr {
            get {
                return ResourceManager.GetString("RecorderStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick the box to record the logs to a file before viewing..
        /// </summary>
        internal static string RecordLogs {
            get {
                return ResourceManager.GetString("RecordLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings back to the default state?.
        /// </summary>
        internal static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotorcraft.
        /// </summary>
        internal static string Rotorcraft {
            get {
                return ResourceManager.GetString("Rotorcraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your current recording?.
        /// </summary>
        internal static string SaveCurrentRecording {
            get {
                return ResourceManager.GetString("SaveCurrentRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning is not supported with Microsoft Flight Simulator 2020. Models are automatically discovered as they appear in the simulator..
        /// </summary>
        internal static string Scan2020 {
            get {
                return ResourceManager.GetString("Scan2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan For Models.
        /// </summary>
        internal static string ScanForModels {
            get {
                return ResourceManager.GetString("ScanForModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first start the simulator before scanning for models..
        /// </summary>
        internal static string ScanWarning {
            get {
                return ResourceManager.GetString("ScanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string ShareAncillarySuffix {
            get {
                return ResourceManager.GetString("ShareAncillarySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string ShareFlightSuffix {
            get {
                return ResourceManager.GetString("ShareFlightSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string ShareNavSuffix {
            get {
                return ResourceManager.GetString("ShareNavSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow shared cockpit with selected user.
        /// </summary>
        internal static string Shortcuts_Allow {
            get {
                return ResourceManager.GetString("Shortcuts_Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand over controls to selected user.
        /// </summary>
        internal static string Shortcuts_Controls {
            get {
                return ResourceManager.GetString("Shortcuts_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter/leave cockpit of selected aircraft.
        /// </summary>
        internal static string Shortcuts_Enter {
            get {
                return ResourceManager.GetString("Shortcuts_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow selected aircraft.
        /// </summary>
        internal static string Shortcuts_Follow {
            get {
                return ResourceManager.GetString("Shortcuts_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the network state on/off.
        /// </summary>
        internal static string Shortcuts_Network {
            get {
                return ResourceManager.GetString("Shortcuts_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the simulator state on/off.
        /// </summary>
        internal static string Shortcuts_Simulator {
            get {
                return ResourceManager.GetString("Shortcuts_Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleProp.
        /// </summary>
        internal static string SingleProp {
            get {
                return ResourceManager.GetString("SingleProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the colour to use when something in JoinFS is active.
        /// </summary>
        internal static string Tip_Active {
            get {
                return ResourceManager.GetString("Tip_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ICAO code for the airport you are controlling.
        /// </summary>
        internal static string Tip_Airport {
            get {
                return ResourceManager.GetString("Tip_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the JoinFS windows in the foreground.
        /// </summary>
        internal static string Tip_AlwaysOnTop {
            get {
                return ResourceManager.GetString("Tip_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let others know that you are providing ATC coverage at an airport or region.
        /// </summary>
        internal static string Tip_ATC {
            get {
                return ResourceManager.GetString("Tip_ATC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all JoinFS windows every 30 seconds.
        /// </summary>
        internal static string Tip_AutoRefresh {
            get {
                return ResourceManager.GetString("Tip_AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create a new session. Others can join using your &apos;Me&apos; address.
        /// </summary>
        internal static string Tip_ButtonCreate {
            get {
                return ResourceManager.GetString("Tip_ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the maximum distance at which aircraft will be injected into the simulator.
        /// </summary>
        internal static string Tip_CircleOfActivity {
            get {
                return ResourceManager.GetString("Tip_CircleOfActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the required Microsoft C++ module for the X-Plane plugin.
        /// </summary>
        internal static string Tip_CPP {
            get {
                return ResourceManager.GetString("Tip_CPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive early notification to try a new version before it is offically released..
        /// </summary>
        internal static string Tip_EarlyUpdate {
            get {
                return ResourceManager.GetString("Tip_EarlyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically adjust other aircraft to compensate for differences in scenery airport elevation.
        /// </summary>
        internal static string Tip_Elevation {
            get {
                return ResourceManager.GetString("Tip_Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the recording stored in the recorder.
        /// </summary>
        internal static string Tip_EndTime {
            get {
                return ResourceManager.GetString("Tip_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the file &apos;euroscope.txt&apos; with current aircraft data for showing in Euroscope.
        /// </summary>
        internal static string Tip_Euroscope {
            get {
                return ResourceManager.GetString("Tip_Euroscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the distance you want your aircraft to be moved behind another aircraft. See View|Aircraft, &apos;Follow&apos; option.
        /// </summary>
        internal static string Tip_Follow {
            get {
                return ResourceManager.GetString("Tip_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The radio frequency you are controlling on.
        /// </summary>
        internal static string Tip_Frequency {
            get {
                return ResourceManager.GetString("Tip_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to join the global public session.
        /// </summary>
        internal static string Tip_GlobalButton {
            get {
                return ResourceManager.GetString("Tip_GlobalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically join the global public session when JoinFS starts.
        /// </summary>
        internal static string Tip_GlobalJoin {
            get {
                return ResourceManager.GetString("Tip_GlobalJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A short description for this hub that will appear in everyone&apos;s hub list.
        /// </summary>
        internal static string Tip_HubAbout {
            get {
                return ResourceManager.GetString("Tip_HubAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional domain name address, for example, &apos;myserver.com&apos;.
        /// </summary>
        internal static string Tip_HubDomain {
            get {
                return ResourceManager.GetString("Tip_HubDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional information about upcoming events or meeting dates and times.
        /// </summary>
        internal static string Tip_HubEvent {
            get {
                return ResourceManager.GetString("Tip_HubEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a public session that will appear in everyone&apos;s hub list. Port Forwarding required. See manual..
        /// </summary>
        internal static string Tip_HubMode {
            get {
                return ResourceManager.GetString("Tip_HubMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public name of this hub that will be shown in everyone&apos;s hub list.
        /// </summary>
        internal static string Tip_HubName {
            get {
                return ResourceManager.GetString("Tip_HubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of a voice server associated with this hub. For example, &quot;ts3.myserver.com&quot;.
        /// </summary>
        internal static string Tip_HubVoice {
            get {
                return ResourceManager.GetString("Tip_HubVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the colour to use when something in JoinFS is inactive or failed.
        /// </summary>
        internal static string Tip_Inactive {
            get {
                return ResourceManager.GetString("Tip_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address of a session and click &apos;Join&apos;.
        /// </summary>
        internal static string Tip_Join {
            get {
                return ResourceManager.GetString("Tip_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to join the session at the given address.
        /// </summary>
        internal static string Tip_JoinButton {
            get {
                return ResourceManager.GetString("Tip_JoinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The colour of the labels of injected aircraft in the simulator.
        /// </summary>
        internal static string Tip_LabelColour {
            get {
                return ResourceManager.GetString("Tip_LabelColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ATC level at which you are controlling.
        /// </summary>
        internal static string Tip_Level {
            get {
                return ResourceManager.GetString("Tip_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify which UDP network port JoinFS will use - default is 6112.
        /// </summary>
        internal static string Tip_LocalPort {
            get {
                return ResourceManager.GetString("Tip_LocalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep looping back to the start of the recording during play back..
        /// </summary>
        internal static string Tip_Loop {
            get {
                return ResourceManager.GetString("Tip_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce the amount of network data used by JoinFS - may affect performance.
        /// </summary>
        internal static string Tip_LowBandwidth {
            get {
                return ResourceManager.GetString("Tip_LowBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your address. Others can join you using this address.
        /// </summary>
        internal static string Tip_Me {
            get {
                return ResourceManager.GetString("Tip_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically scan for models every time JoinFS connects to the flight simulator.
        /// </summary>
        internal static string Tip_ModelScan {
            get {
                return ResourceManager.GetString("Tip_ModelScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow this client to receive more than one aircraft from any other client in a session..
        /// </summary>
        internal static string Tip_MultiObjects {
            get {
                return ResourceManager.GetString("Tip_MultiObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join/leave the session at the given address.
        /// </summary>
        internal static string Tip_NetworkButton {
            get {
                return ResourceManager.GetString("Tip_NetworkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a personal name for others to see in JoinFS.
        /// </summary>
        internal static string Tip_Nickname {
            get {
                return ResourceManager.GetString("Tip_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording the selected aircraft and add them to the existing aircraft already stored in the recorder. Existing aircraft will be also be played back in the simulator during overdub.
        /// </summary>
        internal static string Tip_Overdub {
            get {
                return ResourceManager.GetString("Tip_Overdub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect your session with a password.
        /// </summary>
        internal static string Tip_Password {
            get {
                return ResourceManager.GetString("Tip_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/pause the aircraft stored in the recorder.
        /// </summary>
        internal static string Tip_Play {
            get {
                return ResourceManager.GetString("Tip_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the required plugin for X-Plane.
        /// </summary>
        internal static string Tip_Plugin {
            get {
                return ResourceManager.GetString("Tip_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the IP address of the machine running X-Plane. Leave blank if on the same machine.
        /// </summary>
        internal static string Tip_PluginAddress {
            get {
                return ResourceManager.GetString("Tip_PluginAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current position in the recording. Drag the bar to move forwards and backwards in the recording.
        /// </summary>
        internal static string Tip_Position {
            get {
                return ResourceManager.GetString("Tip_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording the selected aircraft.
        /// </summary>
        internal static string Tip_Record {
            get {
                return ResourceManager.GetString("Tip_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the aircraft altitude as part of the aircraft label.
        /// </summary>
        internal static string Tip_ShowAltitude {
            get {
                return ResourceManager.GetString("Tip_ShowAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the aircraft callsign as part of the aircraft label.
        /// </summary>
        internal static string Tip_ShowCallsign {
            get {
                return ResourceManager.GetString("Tip_ShowCallsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the aircraft distance as part of the aircraft label.
        /// </summary>
        internal static string Tip_ShowDistance {
            get {
                return ResourceManager.GetString("Tip_ShowDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the pilot&apos;s nickname as part of the aircraft label.
        /// </summary>
        internal static string Tip_ShowNickname {
            get {
                return ResourceManager.GetString("Tip_ShowNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show nicknames instead of callsigns in the simulator.
        /// </summary>
        internal static string Tip_ShowNicknames {
            get {
                return ResourceManager.GetString("Tip_ShowNicknames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the aircraft speed as part of the aircraft label.
        /// </summary>
        internal static string Tip_ShowSpeed {
            get {
                return ResourceManager.GetString("Tip_ShowSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect/disconnect the flight simulator.
        /// </summary>
        internal static string Tip_SimulatorButton {
            get {
                return ResourceManager.GetString("Tip_SimulatorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version | open map | total hub users, session users | contribute.
        /// </summary>
        internal static string Tip_Status {
            get {
                return ResourceManager.GetString("Tip_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording/playing the aircraft.
        /// </summary>
        internal static string Tip_Stop {
            get {
                return ResourceManager.GetString("Tip_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable TCAS in X-Plane to allow map support. Aircraft will be acquired by the plugin which may interfere with other plugins..
        /// </summary>
        internal static string Tip_TCAS {
            get {
                return ResourceManager.GetString("Tip_TCAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time since recording/playback started.
        /// </summary>
        internal static string Tip_Time {
            get {
                return ResourceManager.GetString("Tip_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show help when mouse pointer is over window items.
        /// </summary>
        internal static string Tip_ToolTips {
            get {
                return ResourceManager.GetString("Tip_ToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically broadcast VRS TACPAC objects.
        /// </summary>
        internal static string Tip_VRS {
            get {
                return ResourceManager.GetString("Tip_VRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the colour to use when something in JoinFS is waiting to become active.
        /// </summary>
        internal static string Tip_Waiting {
            get {
                return ResourceManager.GetString("Tip_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the file &apos;whazzup.txt&apos; with aircraft data to use in your own online maps.
        /// </summary>
        internal static string Tip_Whazzup {
            get {
                return ResourceManager.GetString("Tip_Whazzup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include all AI aircraft in the &apos;whazzup.txt&apos; file.
        /// </summary>
        internal static string Tip_WhazzupAI {
            get {
                return ResourceManager.GetString("Tip_WhazzupAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include aircraft from all public hubs in the &apos;whazzup.txt&apos; file.
        /// </summary>
        internal static string Tip_WhazzupGlobal {
            get {
                return ResourceManager.GetString("Tip_WhazzupGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable connection to the X-Plane flight simulator.
        /// </summary>
        internal static string Tip_Xplane {
            get {
                return ResourceManager.GetString("Tip_Xplane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwinProp.
        /// </summary>
        internal static string TwinProp {
            get {
                return ResourceManager.GetString("TwinProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Recording.
        /// </summary>
        internal static string UnsavedRecording {
            get {
                return ResourceManager.GetString("UnsavedRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Password.
        /// </summary>
        internal static string VerifyPassword {
            get {
                return ResourceManager.GetString("VerifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        internal static string Voice {
            get {
                return ResourceManager.GetString("Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only get weather observations from an aircraft on the network..
        /// </summary>
        internal static string WeatherObservation {
            get {
                return ResourceManager.GetString("WeatherObservation", resourceCulture);
            }
        }
    }
}
