//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinFS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MigratedSettings {
            get {
                return ((bool)(this["MigratedSettings"]));
            }
            set {
                this["MigratedSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JoinAddress {
            get {
                return ((string)(this["JoinAddress"]));
            }
            set {
                this["JoinAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyIp {
            get {
                return ((string)(this["MyIp"]));
            }
            set {
                this["MyIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Nickname {
            get {
                return ((string)(this["Nickname"]));
            }
            set {
                this["Nickname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AtcAirport {
            get {
                return ((string)(this["AtcAirport"]));
            }
            set {
                this["AtcAirport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HubAddress {
            get {
                return ((string)(this["HubAddress"]));
            }
            set {
                this["HubAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HubName {
            get {
                return ((string)(this["HubName"]));
            }
            set {
                this["HubName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HubAbout {
            get {
                return ((string)(this["HubAbout"]));
            }
            set {
                this["HubAbout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HubVoIP {
            get {
                return ((string)(this["HubVoIP"]));
            }
            set {
                this["HubVoIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HubEvent {
            get {
                return ((string)(this["HubEvent"]));
            }
            set {
                this["HubEvent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AskVersion {
            get {
                return ((string)(this["AskVersion"]));
            }
            set {
                this["AskVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecordingFolder {
            get {
                return ((string)(this["RecordingFolder"]));
            }
            set {
                this["RecordingFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid LastPosition {
            get {
                return ((global::System.Guid)(this["LastPosition"]));
            }
            set {
                this["LastPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XPlanePluginAddress {
            get {
                return ((string)(this["XPlanePluginAddress"]));
            }
            set {
                this["XPlanePluginAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AskSimConnect {
            get {
                return ((bool)(this["AskSimConnect"]));
            }
            set {
                this["AskSimConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortBookmarksColumn {
            get {
                return ((int)(this["SortBookmarksColumn"]));
            }
            set {
                this["SortBookmarksColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoRefresh {
            get {
                return ((bool)(this["AutoRefresh"]));
            }
            set {
                this["AutoRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BookmarksFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["BookmarksFormLocation"]));
            }
            set {
                this["BookmarksFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BookmarksFormSize {
            get {
                return ((global::System.Drawing.Size)(this["BookmarksFormSize"]));
            }
            set {
                this["BookmarksFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AircraftFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["AircraftFormLocation"]));
            }
            set {
                this["AircraftFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size AircraftFormSize {
            get {
                return ((global::System.Drawing.Size)(this["AircraftFormSize"]));
            }
            set {
                this["AircraftFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AddressBookFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["AddressBookFormLocation"]));
            }
            set {
                this["AddressBookFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size AddressBookFormSize {
            get {
                return ((global::System.Drawing.Size)(this["AddressBookFormSize"]));
            }
            set {
                this["AddressBookFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ShortcutsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["ShortcutsFormLocation"]));
            }
            set {
                this["ShortcutsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size ShortcutsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["ShortcutsFormSize"]));
            }
            set {
                this["ShortcutsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SessionFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["SessionFormLocation"]));
            }
            set {
                this["SessionFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size SessionFormSize {
            get {
                return ((global::System.Drawing.Size)(this["SessionFormSize"]));
            }
            set {
                this["SessionFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RecorderFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["RecorderFormLocation"]));
            }
            set {
                this["RecorderFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size RecorderFormSize {
            get {
                return ((global::System.Drawing.Size)(this["RecorderFormSize"]));
            }
            set {
                this["RecorderFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point OptionsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["OptionsFormLocation"]));
            }
            set {
                this["OptionsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size OptionsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["OptionsFormSize"]));
            }
            set {
                this["OptionsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ObjectsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["ObjectsFormLocation"]));
            }
            set {
                this["ObjectsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size ObjectsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["ObjectsFormSize"]));
            }
            set {
                this["ObjectsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MonitorFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MonitorFormLocation"]));
            }
            set {
                this["MonitorFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MonitorFormSize {
            get {
                return ((global::System.Drawing.Size)(this["MonitorFormSize"]));
            }
            set {
                this["MonitorFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MatchingFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MatchingFormLocation"]));
            }
            set {
                this["MatchingFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MatchingFormSize {
            get {
                return ((global::System.Drawing.Size)(this["MatchingFormSize"]));
            }
            set {
                this["MatchingFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Point MainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point HubsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["HubsFormLocation"]));
            }
            set {
                this["HubsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size HubsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["HubsFormSize"]));
            }
            set {
                this["HubsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AtcFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["AtcFormLocation"]));
            }
            set {
                this["AtcFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size AtcFormSize {
            get {
                return ((global::System.Drawing.Size)(this["AtcFormSize"]));
            }
            set {
                this["AtcFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeIgnoredAircraft {
            get {
                return ((bool)(this["IncludeIgnoredAircraft"]));
            }
            set {
                this["IncludeIgnoredAircraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeSimulatorAircraft {
            get {
                return ((bool)(this["IncludeSimulatorAircraft"]));
            }
            set {
                this["IncludeSimulatorAircraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeGlobalAircraft {
            get {
                return ((bool)(this["IncludeGlobalAircraft"]));
            }
            set {
                this["IncludeGlobalAircraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortAircraftColumn {
            get {
                return ((int)(this["SortAircraftColumn"]));
            }
            set {
                this["SortAircraftColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BroadcastTacpack {
            get {
                return ((bool)(this["BroadcastTacpack"]));
            }
            set {
                this["BroadcastTacpack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoBroadcast {
            get {
                return ((bool)(this["AutoBroadcast"]));
            }
            set {
                this["AutoBroadcast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortAtcColumn {
            get {
                return ((int)(this["SortAtcColumn"]));
            }
            set {
                this["SortAtcColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Euroscope {
            get {
                return ((bool)(this["Euroscope"]));
            }
            set {
                this["Euroscope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22800")]
        public int AtcFrequency {
            get {
                return ((int)(this["AtcFrequency"]));
            }
            set {
                this["AtcFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AtcLevel {
            get {
                return ((int)(this["AtcLevel"]));
            }
            set {
                this["AtcLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListIgnoredHubs {
            get {
                return ((bool)(this["ListIgnoredHubs"]));
            }
            set {
                this["ListIgnoredHubs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ListOfflineHubs {
            get {
                return ((bool)(this["ListOfflineHubs"]));
            }
            set {
                this["ListOfflineHubs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortHubsColumn {
            get {
                return ((int)(this["SortHubsColumn"]));
            }
            set {
                this["SortHubsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color ColourActiveBackground {
            get {
                return ((global::System.Drawing.Color)(this["ColourActiveBackground"]));
            }
            set {
                this["ColourActiveBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlText")]
        public global::System.Drawing.Color ColourActiveText {
            get {
                return ((global::System.Drawing.Color)(this["ColourActiveText"]));
            }
            set {
                this["ColourActiveText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color ColourWaitingBackground {
            get {
                return ((global::System.Drawing.Color)(this["ColourWaitingBackground"]));
            }
            set {
                this["ColourWaitingBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HighlightText")]
        public global::System.Drawing.Color ColourWaitingText {
            get {
                return ((global::System.Drawing.Color)(this["ColourWaitingText"]));
            }
            set {
                this["ColourWaitingText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColourInactiveBackground {
            get {
                return ((global::System.Drawing.Color)(this["ColourInactiveBackground"]));
            }
            set {
                this["ColourInactiveBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HighlightText")]
        public global::System.Drawing.Color ColourInactiveText {
            get {
                return ((global::System.Drawing.Color)(this["ColourInactiveText"]));
            }
            set {
                this["ColourInactiveText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chartreuse")]
        public global::System.Drawing.Color ColourLabel {
            get {
                return ((global::System.Drawing.Color)(this["ColourLabel"]));
            }
            set {
                this["ColourLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShortcutNetwork {
            get {
                return ((bool)(this["ShortcutNetwork"]));
            }
            set {
                this["ShortcutNetwork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShortcutSimulator {
            get {
                return ((bool)(this["ShortcutSimulator"]));
            }
            set {
                this["ShortcutSimulator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShortcutAllowShared {
            get {
                return ((bool)(this["ShortcutAllowShared"]));
            }
            set {
                this["ShortcutAllowShared"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShortcutHandOver {
            get {
                return ((bool)(this["ShortcutHandOver"]));
            }
            set {
                this["ShortcutHandOver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShortcutEnter {
            get {
                return ((bool)(this["ShortcutEnter"]));
            }
            set {
                this["ShortcutEnter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShortcutFollow {
            get {
                return ((bool)(this["ShortcutFollow"]));
            }
            set {
                this["ShortcutFollow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolTips {
            get {
                return ((bool)(this["ToolTips"]));
            }
            set {
                this["ToolTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LowBandwidth {
            get {
                return ((bool)(this["LowBandwidth"]));
            }
            set {
                this["LowBandwidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoLog {
            get {
                return ((bool)(this["AutoLog"]));
            }
            set {
                this["AutoLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShareCockpitEveryone {
            get {
                return ((bool)(this["ShareCockpitEveryone"]));
            }
            set {
                this["ShareCockpitEveryone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MultipleObjectsEveryone {
            get {
                return ((bool)(this["MultipleObjectsEveryone"]));
            }
            set {
                this["MultipleObjectsEveryone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GroupObjects {
            get {
                return ((bool)(this["GroupObjects"]));
            }
            set {
                this["GroupObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortObjectsColumn {
            get {
                return ((int)(this["SortObjectsColumn"]));
            }
            set {
                this["SortObjectsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LocalPortEnabled {
            get {
                return ((bool)(this["LocalPortEnabled"]));
            }
            set {
                this["LocalPortEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6112")]
        public ushort LocalPort {
            get {
                return ((ushort)(this["LocalPort"]));
            }
            set {
                this["LocalPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConnectOnLaunch {
            get {
                return ((bool)(this["ConnectOnLaunch"]));
            }
            set {
                this["ConnectOnLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int ActivityCircle {
            get {
                return ((int)(this["ActivityCircle"]));
            }
            set {
                this["ActivityCircle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Atc {
            get {
                return ((bool)(this["Atc"]));
            }
            set {
                this["Atc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Hub {
            get {
                return ((bool)(this["Hub"]));
            }
            set {
                this["Hub"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Whazzup {
            get {
                return ((bool)(this["Whazzup"]));
            }
            set {
                this["Whazzup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WhazzupGlobal {
            get {
                return ((bool)(this["WhazzupGlobal"]));
            }
            set {
                this["WhazzupGlobal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Global {
            get {
                return ((bool)(this["Global"]));
            }
            set {
                this["Global"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HubsFormOpen {
            get {
                return ((bool)(this["HubsFormOpen"]));
            }
            set {
                this["HubsFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BookmarksFormOpen {
            get {
                return ((bool)(this["BookmarksFormOpen"]));
            }
            set {
                this["BookmarksFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AircraftFormOpen {
            get {
                return ((bool)(this["AircraftFormOpen"]));
            }
            set {
                this["AircraftFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AtcFormOpen {
            get {
                return ((bool)(this["AtcFormOpen"]));
            }
            set {
                this["AtcFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ObjectsFormOpen {
            get {
                return ((bool)(this["ObjectsFormOpen"]));
            }
            set {
                this["ObjectsFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecorderFormOpen {
            get {
                return ((bool)(this["RecorderFormOpen"]));
            }
            set {
                this["RecorderFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SessionFormOpen {
            get {
                return ((bool)(this["SessionFormOpen"]));
            }
            set {
                this["SessionFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MonitorFormOpen {
            get {
                return ((bool)(this["MonitorFormOpen"]));
            }
            set {
                this["MonitorFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatchingFormOpen {
            get {
                return ((bool)(this["MatchingFormOpen"]));
            }
            set {
                this["MatchingFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShortcutsFormOpen {
            get {
                return ((bool)(this["ShortcutsFormOpen"]));
            }
            set {
                this["ShortcutsFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptionsFormOpen {
            get {
                return ((bool)(this["OptionsFormOpen"]));
            }
            set {
                this["OptionsFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ModelScanOnConnection {
            get {
                return ((bool)(this["ModelScanOnConnection"]));
            }
            set {
                this["ModelScanOnConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11, 115, 16")]
        public global::System.Drawing.Color CommsTextColour {
            get {
                return ((global::System.Drawing.Color)(this["CommsTextColour"]));
            }
            set {
                this["CommsTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CommsBackColour {
            get {
                return ((global::System.Drawing.Color)(this["CommsBackColour"]));
            }
            set {
                this["CommsBackColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortUsersColumn {
            get {
                return ((int)(this["SortUsersColumn"]));
            }
            set {
                this["SortUsersColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SessionChat {
            get {
                return ((bool)(this["SessionChat"]));
            }
            set {
                this["SessionChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNicknames {
            get {
                return ((bool)(this["ShowNicknames"]));
            }
            set {
                this["ShowNicknames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TCAS {
            get {
                return ((bool)(this["TCAS"]));
            }
            set {
                this["TCAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AtcWarning {
            get {
                return ((bool)(this["AtcWarning"]));
            }
            set {
                this["AtcWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WhazzupAI {
            get {
                return ((bool)(this["WhazzupAI"]));
            }
            set {
                this["WhazzupAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCallsign {
            get {
                return ((bool)(this["ShowCallsign"]));
            }
            set {
                this["ShowCallsign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDistance {
            get {
                return ((bool)(this["ShowDistance"]));
            }
            set {
                this["ShowDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAltitude {
            get {
                return ((bool)(this["ShowAltitude"]));
            }
            set {
                this["ShowAltitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSpeed {
            get {
                return ((bool)(this["ShowSpeed"]));
            }
            set {
                this["ShowSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ElevationCorrection {
            get {
                return ((bool)(this["ElevationCorrection"]));
            }
            set {
                this["ElevationCorrection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int FollowDistance {
            get {
                return ((int)(this["FollowDistance"]));
            }
            set {
                this["FollowDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XPlane {
            get {
                return ((bool)(this["XPlane"]));
            }
            set {
                this["XPlane"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShortcutEnterCockpit {
            get {
                return ((bool)(this["ShortcutEnterCockpit"]));
            }
            set {
                this["ShortcutEnterCockpit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTRL+N")]
        public string ShortcutNetworkKey {
            get {
                return ((string)(this["ShortcutNetworkKey"]));
            }
            set {
                this["ShortcutNetworkKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTRL+S")]
        public string ShortcutSimulatorKey {
            get {
                return ((string)(this["ShortcutSimulatorKey"]));
            }
            set {
                this["ShortcutSimulatorKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTRL+A")]
        public string ShortcutAllowSharedKey {
            get {
                return ((string)(this["ShortcutAllowSharedKey"]));
            }
            set {
                this["ShortcutAllowSharedKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTRL+H")]
        public string ShortcutHandOverKey {
            get {
                return ((string)(this["ShortcutHandOverKey"]));
            }
            set {
                this["ShortcutHandOverKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTRL+E")]
        public string ShortcutEnterKey {
            get {
                return ((string)(this["ShortcutEnterKey"]));
            }
            set {
                this["ShortcutEnterKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTRL+F")]
        public string ShortcutFollowKey {
            get {
                return ((string)(this["ShortcutFollowKey"]));
            }
            set {
                this["ShortcutFollowKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileFlightPlanOnStart {
            get {
                return ((bool)(this["FileFlightPlanOnStart"]));
            }
            set {
                this["FileFlightPlanOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XPlaneFolder {
            get {
                return ((string)(this["XPlaneFolder"]));
            }
            set {
                this["XPlaneFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Loop {
            get {
                return ((bool)(this["Loop"]));
            }
            set {
                this["Loop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EarlyUpdate {
            get {
                return ((bool)(this["EarlyUpdate"]));
            }
            set {
                this["EarlyUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0.0")]
        public string AskImport {
            get {
                return ((string)(this["AskImport"]));
            }
            set {
                this["AskImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GenerateCsl {
            get {
                return ((bool)(this["GenerateCsl"]));
            }
            set {
                this["GenerateCsl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SkipCsl {
            get {
                return ((bool)(this["SkipCsl"]));
            }
            set {
                this["SkipCsl"] = value;
            }
        }
    }
}
